@startuml
scale 8192*8192

package date_svc{
    class DateSvc
}

class DateSvc{
    - _raw_data_svc
    - _setTradeDays()
    + setMode()
    + formatIndex()
    + getAllTradeDays()
    + cutDataWithIndex()
    + cutDataWithWindow()
    + cutDataWithRange()
    + getIndexWithWindow()
    + getIndexWithRange()
    + getIndex()
    + cutData()
}

@enduml